{"asctime": "2024-06-05 T00:15:43+0530", "message": "An Error Occured: 'NoneType' object is not iterable", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Celebal data\\Clients\\Telecom Egypt\\fastapi\\Telecom%20Egypt%20Internal\\main.py\", line 337, in pipeline_after_transcription\n    for ls in result[\"keyPhrases_ls\"]:\nTypeError: 'NoneType' object is not iterable", "location": "main.py - pipeline_after_transcription"}
