{"asctime": "2024-06-12 T17:46:28+0530", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Celebal data\\Clients\\Telecom Egypt\\fastapi\\Telecom%20Egypt%20Internal\\main.py\", line 212, in audios_main\n    self.add_mapping_to_excel()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'Main' object has no attribute 'add_mapping_to_excel'", "location": "main.py-audios_main"}
